PowerGridMVC/Controllers/DistiGridController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Contract;
using Domain;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Newtonsoft.Json.Schema;
using PowerGridMVC.Models;

namespace PowerGridMVC.Controllers
{
    public class DistiGridController : Controller
    {
        private IGeoRepository _geoRepository;
        private IAreaRepository _areaRepository;
        private ISubsidiaryRepository _subsidiaryRepository;

        public DistiGridController(IGeoRepository geoRepository, IAreaRepository areaRepository,ISubsidiaryRepository subsidiaryRepository)
        {
            _geoRepository = geoRepository;
            _areaRepository = areaRepository;
            _subsidiaryRepository = subsidiaryRepository;
        }
        // GET: /DistiGrid/
        public ActionResult Index()
        {
            var distiGridModel=new DistiGridModel();
            return View("Index",distiGridModel);
        }

        public JsonResult GetCascadeCategories()
        {
            var geos = _geoRepository.All();
            return Json(geos.Select(c => new { Id = c.Id, Name = c.Name }), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAreaByGeo(int id)
        {
            var areas = _areaRepository.AreaByGeo(id).Where(x => x.GeoId==id);

            return Json(areas.Select(p => new { Id = p.Id, Name = p.Name}), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSubsdiaryByArea(int areaId)
        {
            var subsidiaries = _subsidiaryRepository.SubsidiaryByArea(areaId).Where(x => x.AreaId==areaId);

            return Json(subsidiaries.Select(p => new { Id = p.Id, Name = p.Name }), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Details()
        {
            return View();
        }

        public ActionResult Load()
        {
            return View();
        }
        // public ActionResult Editing_Read([DataSourceRequest] DataSourceRequest request)
        //{
        //    //run the appropriate sql to get all the distributors for that cell
        //     var sqlcommand = "select * from dstsalesl100"; //TODO: change this sql once schema is ready
             
        //     using (SqlConnection connection = new SqlConnection("Data Source=110LAP279;Initial Catalog=PartnerGrid;Integrated Security=True;"))
        //     {
        //         using (SqlCommand command = new SqlCommand("select Id,Name from Geo", connection))
        //         {
        //             connection.Open();
        //             SqlDataReader reader = command.ExecuteReader();
        //             while (reader.Read())
        //             {
        //                 //read the required fields
        //             }

        //         }
        //     }

        //     return null;
        //}

        //[AcceptVerbs(HttpVerbs.Post)]
        //public ActionResult Editing_Create([DataSourceRequest] DataSourceRequest request, [Bind(Prefix = "models")]IEnumerable<AccountModel> distributors)
        //{
        //    var results = new List<AccountModel>();

        //    if (distributors != null && ModelState.IsValid)
        //    {
        //        foreach (var distributor in distributors)
        //        {
        //            productService.Create(distributor);
        //            results.Add(distributor);
        //        }
        //    }

        //    return Json(results.ToDataSourceResult(request, ModelState));
        //}

        //[AcceptVerbs(HttpVerbs.Post)]
        //public ActionResult Editing_Update([DataSourceRequest] DataSourceRequest request, [Bind(Prefix = "models")]IEnumerable<AccountModel> distributors)
        //{
        //    if (distributors != null && ModelState.IsValid)
        //    {
        //   foreach (var distributor in distributors)
        //        {
        //            productService.Update(distributor);
        //        }
        //    }

        //    return Json(distributors.ToDataSourceResult(request, ModelState));
        //}

        //[AcceptVerbs(HttpVerbs.Post)]
        //public ActionResult Editing_Destroy([DataSourceRequest] DataSourceRequest request, [Bind(Prefix = "models")]IEnumerable<AccountModel> distributors)
        //{            
        //    if (distributors.Any())
        //    {
        //        foreach (var product in distributors)
        //        {
        //            productService.Destroy(product);
        //        }
        //    }

        //    return Json(distributors.ToDataSourceResult(request,ModelState));
        //}
    }
}
    

PowerGridMVC/Controllers/ResellerGridController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Contract;
using PowerGridMVC.Models;

namespace PowerGridMVC.Controllers
{
    public class ResellerGridController : Controller
    {
        private ITimeZoneRepository _timeZoneRepository;

        public ResellerGridController(ITimeZoneRepository timeZoneRepository )
        {
            _timeZoneRepository = timeZoneRepository;
        }
        //
        // GET: /ResellerGrid/
        public ActionResult Index()
        {
            var resellerGridModel = new ResellerGridModel();
            return View("Index", resellerGridModel);
            
        }
        public JsonResult GetCascadeCategories()
        {
            var geos = _timeZoneRepository.All();
            return Json(geos.Select(c => new { Geo=c.Geo}), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAreaByGeo(string Name)
        {
            var areas = _timeZoneRepository.AreaByGeo(Name).Where(x => x.Geo == Name);

            return Json(areas.Select(p => new { Area = p.Area }), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSubsdiaryByArea(string areaName)
        {
            var subsidiaries = _timeZoneRepository.SubsidiaryByArea(areaName).Where(x => x.Area == areaName);

            return Json(subsidiaries.Select(p => new {Subsidiary = p.Subsidiary }), JsonRequestBehavior.AllowGet);
        }

	}
}

PowerGridMVC/Views/ResellerGrid/Index.cshtml
@model PowerGridMVC.Models.ResellerGridModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="timeSpanFrame">
        <div class="timeSpanLeft">
            <h2>Time Period</h2>
        </div>
        <div class="timeSpanRight">
            <div class="timePeriod">
                <ul>
                    <li class="selected" @Html.ActionLink("Jun FY14", "Index", "DistiGrid")></li>
                    <li>Jul FY15</li>
                    <li>Aug FY15</li>
                    <li>Sep FY15</li>
                    <li>Oct FY15</li>
                    <li>Nov FY15</li>
                    <li>Dec FY15</li>
                    <li>Jan FY15</li>
                    <li>Feb FY15</li>
                    <li>Mar FY15</li>
                    <li>Apr FY15</li>
                    <li>May FY15</li>
                    <li>Jun FY15</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="breadCrumbs">&nbsp;</div>
    <div class="frame">
        <div class="frameLeft">
            <h2>Filters</h2>
            <div class="filterGroupSection">
                <div class="filterGroup">
                    <div>

                        <label> TimeZone </label>
                        @(Html.Kendo().DropDownList()
                                  .Name("tzName")
                                  .HtmlAttributes(new { style = "width:250px" })
                                  .OptionLabel("Select TimeZone...")
                                  .DataTextField("Geo")
                                                  .DataValueField("Geo")
                                  .DataSource(source => source.Read(read => read.Action("GetCascadeCategories", "ResellerGrid")))
                        )


                        <label> Area </label>
                        @(Html.Kendo().DropDownList()
                                  .Name("areaName")
                                  .HtmlAttributes(new { style = "width:250px" })
                                  .OptionLabel("Select Area...")
                                  .DataTextField("Area")
                                                  .DataValueField("Area")
                                  .DataSource(source => source.Read(read => read.Action("GetAreaByGeo", "ResellerGrid")
                                      .Data("filterArea"))
                                      .ServerFiltering(true))
                                  .Enable(false)
                                  .AutoBind(false)
                                  .CascadeFrom("tzName")
                        )
                        <script>
                            function filterArea() {
                                return {
                                    Name: $("#tzName").val()
                                };
                            }
                        </script>

                        <label> Subsidiary </label>
                        @(Html.Kendo().DropDownList()
                                  .Name("subsidiaryName")
                                  .HtmlAttributes(new { style = "width:250px" })
                                  .OptionLabel("Select Subsdiary...")
                                  .DataTextField("Subsidiary")
                                                  .DataValueField("Subsidiary")
                                  .DataSource(source => source.Read(read => read.Action("GetSubsdiaryByArea", "ResellerGrid")
                                      .Data("filterSubsidiary"))
                                      .ServerFiltering(true))
                                  .Enable(false)
                                  .AutoBind(false)
                                  .CascadeFrom("areaName")
                        )
                        <script>
                            function filterSubsidiary() {
                                return {
                                    areaName: $("#areaName").val()
                                };
                            }
                        </script>

                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>


</body>
</html>